<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

namespace Poyu\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>poyu.grpc.ExampleResponse</code>
 */
class ExampleResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 c = 1;</code>
     */
    private $c = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $c
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Example::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 c = 1;</code>
     * @return int|string
     */
    public function getC()
    {
        return $this->c;
    }

    /**
     * Generated from protobuf field <code>uint64 c = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setC($var)
    {
        GPBUtil::checkUint64($var);
        $this->c = $var;

        return $this;
    }

}

