<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: example.proto

namespace Poyu\Grpc;

use Spiral\GRPC;

interface ExampleServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "poyu.grpc.ExampleService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ExampleRequest $in
    * @return ExampleResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Calculate(GRPC\ContextInterface $ctx, ExampleRequest $in): ExampleResponse;
}
