<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

namespace GPBMetadata;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acc010a0d6578616d706c652e70726f746f1209706f79752e6772706322" .
            "320a0e4578616d706c655265717565737412090a01611801200128041209" .
            "0a0162180220012804120a0a026f70180320012809221c0a0f4578616d70" .
            "6c65526573706f6e736512090a016318012001280432560a0e4578616d70" .
            "6c655365727669636512440a0943616c63756c61746512192e706f79752e" .
            "677270632e4578616d706c65526571756573741a1a2e706f79752e677270" .
            "632e4578616d706c65526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

